name: Bump version

on:
  push:
    branches: [main]

env:
  MAJOR: 0
  MINOR: 4

jobs:
  deploy_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set env
        run: echo "NEXT_VERSION=$(./next-version.sh "${MAJOR}.${MINOR}")" >> $GITHUB_ENV
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: "{{env.NEXT_VERSION}}"
