name: Release

on:
  push:
    tags:
      - v**

jobs:
  publish:
    needs: [check, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install hatch
      - name: Build
        run: |
          hatch build --target wheel
      - name: Publish
        env:
          HATCH_INDEX_USER: "__token__"
          HATCH_INDEX_AUTH: ${{ secrets.PYPI_TOKEN }}
          HATCH_INDEX_REPO: main
        run: hatch publish
